CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    phone VARCHAR2(100),
    birth DATE,
    address VARCHAR2(255),
    passwd VARCHAR2(100),
    PRIMARY KEY (id)
);